### PR TITLE
update question groups to surveys

### PR DESCRIPTION
**Pull request by chukitow**
I was reviewing the project and I found that you were looking rename **question groups** to **surveys** so I did it :)

### CODE REVIEW

**Comment by iffyuva** [comment]
@chukitow thanks for the PR. please take a look at ci failures?

**Comment by chukitow** [comment]
All the build needs to be green ? cuz it only fails on 2.0.0. 2.1.10 & 2.3.1 @iffyuva

**Comment by iffyuva** [comment]
@chukitow for now we require all builds to be green, since builds are already green on master

**Comment by chukitow** [comment]
ok, I'll research why it is failing in those builds.

**Comment by chukitow** [comment]
@iffyuva done, all the builds are green now :)

**Comment by iffyuva** [comment]
thanks @chukitow will review this after office hours today 👍

**Comment by iffyuva** [comment]
@chukitow merged :). Thanks. i was also thinking of renaming answer_groups to attempts. would you like to take it up?

**Comment by chukitow** [comment]
Perfect, if I can I'll spend part of my free time renaming answer_groups :)

**Pull request merged**
