### PR TITLE
Question sorting

### PR DESCRIPTION
**Pull request by tg44**
Implemented question sorting.

### CODE REVIEW

**Comment by tg44** [comment]
Its coud be possible that the  rapidfire.gemspec file need only just responders and not 2.0. I think its mergeable if sb resolve that.

**Comment by iffyuva** [comment]
@tg44 are you talking about support for rails 4.2.0 ?

**Comment by tg44** [comment]
Yepp, if you see I mistakely hardcoded the responders version, I think if you get out the hardcoded version number everything will be fine...

**Comment by iffyuva** [comment]
@tg44 can you check why specs are failing?

**Comment by iffyuva** [comment]
@tg44 im not familiar with changes that have gone into rails 4.2 yet, i will take a look, and get back to you. thanks.

**Comment by tg44** [comment]
Its better a bit, but I need to working on a bit more...

**Comment by tg44** [comment]
Building a virtual machine with multiple rails version support in the first time not so easy.

So the problem is, @sandrew using in 35a86d1 a becomes! function, what was appeared in 4.0.2.
(http://apidock.com/rails/v4.0.2/ActiveRecord/Persistence/becomes!)

I will patch it, my main problem was that the 30b66a3 passed so I thought I made some specific mistake.

**Comment by tg44** [comment]
4.2 works fine, 3.2 works fine, 4.0.13 @question.save not saving the question_group_id to the db.

**Pull request closed without merging**
